version: "2"

run:
    timeout: 5m

linters:
    enable:
        - bodyclose
        - dogsled
        - durationcheck
        - exhaustive
        - gocritic
        - gomoddirectives
        - goprintffuncname
        - govet
        - importas
        - ineffassign
        - makezero
        - misspell
        - nakedret
        - nilerr
        - noctx
        - nolintlint
        - prealloc
        - predeclared
        - revive
        - rowserrcheck
        - sqlclosecheck
        - staticcheck
        - tparallel
        - unconvert
        - unparam
        - unused
        - wastedassign
        - whitespace

        - gosec

        - errcheck
        - errorlint

        - thelper

        - gocyclo

    exclusions:
        rules:
            -   linters:
                    - errcheck
                    - noctx
                path: _test.go
        presets:
            - std-error-handling

    settings:
        revive:
            rules:
                -   name: blank-imports
                -   name: context-as-argument
                    arguments:
                        -   allowTypesBefore: "*testing.T"
                -   name: context-keys-type
                -   name: dot-imports
                -   name: empty-block
                -   name: error-naming
                -   name: error-return
                -   name: error-strings
                -   name: errorf
                -   name: exported
                    arguments:
                        - "sayRepetitiveInsteadOfStutters"  # make error messages clearer
                -   name: increment-decrement
                -   name: indent-error-flow
                -   name: package-comments
                    disabled: true
                -   name: range
                -   name: redefines-builtin-id
                -   name: superfluous-else
                -   name: time-naming
                -   name: unexported-return
                -   name: unreachable-code
                -   name: unused-parameter
                -   name: var-declaration
                -   name: var-naming

        misspell:
            locale: US
        nolintlint:
            allow-unused: false # report any unused nolint directives
            require-specific: false # don't require nolint directives to be specific about which linter is being skipped
        gocritic:
            # Enable multiple checks by tags. See "Tags" section in https://github.com/go-critic/go-critic#usage.
            enabled-tags:
                - diagnostic
                - experimental
                - opinionated
                - style
            disabled-checks:
                - importShadow
                - unnamedResult

formatters:
    enable:
        - gci
        - gofmt
        - gofumpt
        - goimports
        - golines

    settings:
        gci:
            sections:
                - standard
                - default
                - localmodule